[package]
name = "security-framework-sys"
version = "0.2.1"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Security Framework bindings"
repository = "https://github.com/sfackler/rust-security-framework"
documentation = "https://sfackler.github.io/rust-security-framework/doc/v0.2/security_framework_sys"
readme = "../README.md"
keywords = ["OSX", "iOS", "TLS", "SSL", "crypto"]
build = "build.rs"

[dependencies]
libc = "0.2"
core-foundation-sys = "0.5.1"

[features]
OSX_10_9 = []
OSX_10_10 = ["OSX_10_9"]
OSX_10_11 = ["OSX_10_10"]
OSX_10_12 = ["OSX_10_11"]
