[package]
name = "security-framework-sys"
version = "2.17.0"
authors = ["Steven Fackler <sfackler@gmail.com>", "Kornel <kornel@geekhood.net>"]
license = "MIT OR Apache-2.0"
description = "Apple `Security.framework` low-level FFI bindings"
repository = "https://github.com/kornelski/rust-security-framework"
homepage = "https://lib.rs/crates/security-framework-sys"
readme = "README.md"
keywords = ["ffi", "iOS", "TLS", "SSL", "crypto"]
categories = ["os::macos-apis", "external-ffi-bindings"]
edition = "2021"
rust-version = "1.70"

[dependencies]
core-foundation-sys = "0.8.7"
libc = "0.2.150"

[features]
default = ["OSX_10_13"]
# Always enabled. No-op.
OSX_10_9 = []
# Always enabled. No-op.
OSX_10_10 = []
# Always enabled. No-op.
OSX_10_11 = []
# Always enabled. No-op.
OSX_10_12 = []
# Always enabled. No-op.
OSX_10_13 = []
# Always enabled. No-op.
OSX_10_14 = []
# Enable APIs that require macOS 10.15
OSX_10_15 = []
# Enable features that require macOS 12
macos-12 = []

[package.metadata.docs.rs]
targets = ["x86_64-apple-darwin", "aarch64-apple-ios"]

[badges]
maintenance = { status = "looking-for-maintainer" }

[lints]
workspace = true
