[package]
name = "systest"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@palantir.com>"]

[dependencies]
core-foundation-sys = "0.5"
security-framework-sys = { path = "../security-framework-sys" }
libc = "0.2"

[build-dependencies]
ctest = "0.1"

[features]
OSX_10_9 = ["security-framework-sys/OSX_10_9"]
OSX_10_10 = ["OSX_10_9", "security-framework-sys/OSX_10_10"]
OSX_10_11 = ["OSX_10_10", "security-framework-sys/OSX_10_11"]
OSX_10_12 = ["OSX_10_11", "security-framework-sys/OSX_10_12"]
OSX_10_13 = ["OSX_10_12", "security-framework-sys/OSX_10_13"]
